org.gradle.jvmargs=-Djavax.net.ssl.trustStore=gradle/certs/gradle-truststore.p12 -Djavax.net.ssl.trustStoreType=PKCS12 -Djava.net.useSystemProxies=true -Dfile.encoding=UTF-8
systemProp.javax.net.ssl.trustStore=gradle/certs/gradle-truststore.p12
systemProp.javax.net.ssl.trustStoreType=PKCS12
systemProp.java.net.useSystemProxies=true
kotlin.compiler.execution.strategy=in-process
